### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#54]
- [x] Provide a hello world example in the README so users can get a feel for the library whilst browsing the GitHub repo #61

- [x] :large_blue_circle: Provide an entire maven and gradle dependency block (with version) that can be copied into a pom.xml or build.gradle file
- [x] Expand WEBIRC page, explain what WEBIRC is #58
- [x] Docs on using SASL, mechanisms available, emphasising TLS use
- [x] ECDSA docs (see PR #53)

Thoughts?

**Comment by mbax** [comment]
I'd like to hold off on the dependency block until release, so I don't have to include the repository section. Otherwise, I agree. :3

**Comment by lol768** [comment]
Thanks!
